[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "exprim"
version = "4.0.0"
description = "EXPrimitives"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyYAML",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["exprim*"]
